// Ejemplo de datos para las tarjetas (puedes adaptar esto según tus necesidades)
const cardsData = [
    {
      imageSrc: "../img/2023/twi-yaba.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 10-12-2023",
      name: "Twi-Yaba",
      status: "Finalizado",
      availability: "Disponible 1 capitulo",
    },
    {
      imageSrc: "../img/2023/dr-stone-new-world-part-2.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 12-10-2023",
      name: "Dr. Stone: New World Part 2",
      status: "Finalizado",
      availability: "Disponible 11 capitulos",
    },
    {
      imageSrc: "../img/2023/hoshikuzu-telepath.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 09-10-2023",
      name: "Hoshikuzu Telepath",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/kimi-no-koto-ga-daidaidaidaidaisuki-na-100-nin-no-kanojo.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 08-10-2023",
      name: "kimi-no-koto-ga-daidaidaidaidaisuki-na-100-nin-no-kanojo.jpg",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    
    {
      imageSrc: "../img/2023/spy-x-family-season-2.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 07-10-2023",
      name: "Spy x Family Season 2",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/kanojo-mo-kanojo-2nd-season.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 07-10-2023",
      name: "Kanojo mo Kanojo 2nd Season",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/tate-no-yuusha-no-nariagari-season-3.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 06-10-2023",
      name: "Tate no Yuusha no Nariagari Season 3",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/keikenzumi-na-kimi-to-keiken-zero-na-ore-ga-otsukiai-suru-hanashi.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 06-10-2023",
      name: "Keikenzumi na Kimi to, Keiken Zero na Ore ga, Otsukiai suru Hanashi",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/rail-romanesque-2.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 06-10-2023",
      name: "Rail Romanesque 2",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/Mahoutsukai-no-Yome-Season-2-Part-2.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 05-10-2023",
      name: "Mahoutsukai no Yome Season 2 Part 2",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/kizuna-no-allele-season-2.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 05-10-2023",
      name: "Kizuna no Allele Season 2",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/kage-no-jitsuryokusha-ni-naritakute-2nd-season.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 04-10-2023",
      name: "Kage no Jitsuryokusha ni Naritakute! 2nd Season",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/tokyo-revengers-tenjiku-hen.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 04-10-2023",
      name: "Tokyo Revengers: Tenjiku-hen",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/Watashi-no-Oshi-wa-Akuyaku-Reijou.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 03-10-2023",
      name: "Watashi no Oshi wa Akuyaku Reijou",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/Shy.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 03-10-2023",
      name: "Shy",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/hibike-euphonium-ensemble-contest-hen.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 04-10-2023",
      name: "Hibike! Euphonium: Ensemble Contest-hen",
      status: "Finalizado",
      availability: "Disponible 1 capitulo",
    },
    {
      imageSrc: "../img/2023/azur-lane-queens-orders.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 27-07-2023",
      name: "Azur Lane: Queen's Orders",
      status: "Finalizado",
      availability: "Disponible 2 capitulos",
    },
    {
      imageSrc: "../img/2023/5-toubun-no-hanayome.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 14-07-2023",
      name: "5-toubun no Hanayome∽",
      status: "Finalizado",
      availability: "Disponible 2 capitulos",
    },
    {
      imageSrc: "../img/2023/hataraku-maou-sama-2nd-season.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 13-07-2023",
      name: "Hataraku Maou-sama!! 2nd Season",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/bungou-stray-dogs-5th-season.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 12-07-2023",
      name: "Bungou Stray Dogs 5th Season",
      status: "Finalizado",
      availability: "Disponible 11 capitulos",
    },
    {
      imageSrc: "../img/2023/tonikaku-kawaii-joshikou-hen.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 12-07-2023",
      name: "Tonikaku Kawaii: Joshikou-hen",
      status: "Finalizado",
      availability: "Disponible 2 capitulos",
    },
    {
      imageSrc: "../img/2023/shuumatsu-no-walkre-ii-part-2.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 12-07-2023",
      name: "Shuumatsu no Walküre II Part 2",
      status: "Finalizado",
      availability: "Disponible 5 capitulos",
    },
    {
      imageSrc: "../img/2023/zom-100-zombie-ni-naru-made-ni-shitai-100-no-koto.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 09-07-2023",
      name: "Zom 100: Zombie ni Naru made ni Shitai 100 no Koto",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/kanojo-okarishimasu-3rd-season.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 08-07-2023",
      name: "Kanojo, Okarishimasu 3rd Season",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/liar-liar.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 08-07-2023",
      name: "Liar Liar",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/nanatsu-no-maken-ga-shihai-suru.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión: 08-07-2023",
      name: "Nanatsu no Maken ga Shihai suru",
      status: "Finalizado",
      availability: "Disponible 15 capitulos",
    },
    {
      imageSrc: "../img/2023/sugar-apple-fairy-tale-part-2.jpg", /*empezar desde el primero https://jkanime.net/directorio/8/ Sugar Apple Fairy Tale Part 2*/
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Sugar Apple Fairy Tale Part 2",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/watashi-no-shiawase-na-kekkon.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Watashi no Shiawase na Kekkon",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/suki-na-ko-ga-megane-wo-wasureta.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Suki na Ko ga Megane wo Wasureta",
      status: "Finalizado",
      availability: "Disponible 13 capitulos",
    },
    {
      imageSrc: "../img/2023/yumemiru-danshi-wa-genjitsushugisha.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Yumemiru Danshi wa Genjitsushugisha",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/masamune-kun-no-revenge-r.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Masamune-kun no Revenge R",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/spy-kyoushitsu-2nd-season.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Spy Kyoushitsu 2nd Season",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/bang-dream-its-mygo.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "BanG Dream! It's MyGO!!!!!",
      status: "Finalizado",
      availability: "Disponible 13 capitulos",
    },
    {
      imageSrc: "../img/2023/genjitsu-no-yohane-sunshine-in-the-mirror.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Genjitsu no Yohane: Sunshine in the Mirror",
      status: "Finalizado",
      availability: "Disponible 13 capitulos",
    },
    {
      imageSrc: "../img/2023/seishun-buta-yarou-wa-odekake-sister-no-yume-wo-minai.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Seishun Buta Yarou wa Odekake Sister no Yume wo Minai",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/yahari-ore-no-seishun-love-comedy-wa-machigatteiru-kan-dakara-shishunki-wa-owarazu-ni-seishun-wa-tsuzuiteiku.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Yahari Ore no Seishun Love Comedy wa Machigatteiru. Kan: Dakara, Shishunki wa Owarazu ni, Seishun wa Tsuzuiteiku",
      status: "Finalizado",
      availability: "Disponible 1 capitulo",
    },
    {
      imageSrc: "../img/2023/oshi-no-ko.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Oshi no Ko",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/edens-zero-2nd-season.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Edens Zero 2nd Season",
      status: "Finalizado",
      availability: "Disponible 25 capitulos",
    },
    {
      imageSrc: "../img/2023/tonikaku-kawaii-2nd-season.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Tonikaku Kawaii 2nd Season",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/megami-no-caf-terrace.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Megami no Café Terrace",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/dr-stone-new-world.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Dr. Stone: New World",
      status: "Finalizado",
      availability: "Disponible 11 capitulos",
    },
    {
      imageSrc: "../img/2023/mahoutsukai-no-yome-season-2.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Mahoutsukai no Yome Season 2",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/kizuna-no-allele.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Kizuna no Allele",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/isekai-wa-smartphone-to-tomo-ni-2.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Isekai wa Smartphone to Tomo ni. 2",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/yamada-kun-to-lv999-no-koi-wo-suru.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Yamada-kun to Lv999 no Koi wo Suru",
      status: "Finalizado",
      availability: "Disponible 13 capitulos",
    },
    {
      imageSrc: "../img/2023/boku-no-kokoro-no-yabai-yatsu.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Boku no Kokoro no Yabai Yatsu",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/jijou-wo-shiranai-tenkousei-ga-guigui-kuru.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Jijou wo Shiranai Tenkousei ga Guigui Kuru",
      status: "Finalizado",
      availability: "Disponible 13 capitulos",
    },
    {
      imageSrc: "../img/2023/inu-ni-nattara-suki-na-hito-ni-hirowareta-specials.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Inu ni Nattara Suki na Hito ni Hirowareta. Specials",
      status: "Finalizado",
      availability: "Disponible 2 capitulos",
    },
    {
      imageSrc: "../img/2023/shuumatsu-no-walkre-ii.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Shuumatsu no Walküre II",
      status: "Finalizado",
      availability: "Disponible 15 capitulos",
    },
    {
      imageSrc: "../img/2023/shin-shinka-no-mi-shiranai-uchi-ni-kachigumi-jinsei.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Shin Shinka no Mi: Shiranai Uchi ni Kachigumi Jinsei",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/d4dj-all-mix.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "D4DJ All Mix",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/maou-gakuin-no-futekigousha-shijou-saikyou-no-maou-no-shiso-tensei-shite-shison-tachi-no-gakkou-e-kayou-ii.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Maou Gakuin no Futekigousha: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e Kayou II",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/tokyo-revengers-seiya-kessen-hen.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Tokyo Revengers: Seiya Kessen-hen",
      status: "Finalizado",
      availability: "Disponible 13 capitulos",
    },
    {
      imageSrc: "../img/2023/otonari-no-tenshi-sama-ni-itsunomanika-dame-ningen-ni-sareteita-ken.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Otonari no Tenshi-sama ni Itsunomanika Dame Ningen ni Sareteita Ken",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/inu-ni-nattara-suki-na-hito-ni-hirowareta.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Inu ni Nattara Suki na Hito ni Hirowareta",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/buddy-daddies.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Buddy Daddies",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/sugar-apple-fairy-tale.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Sugar Apple Fairy Tale",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/spy-kyoushitsu.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Spy Kyoushitsu",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2023/bungou-stray-dogs-4th-season.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Bungou Stray Dogs 4th Season",
      status: "Finalizado",
      availability: "Disponible 13 capitulos",
    },
    {
      imageSrc: "../img/2023/tomo-chan-wa-onnanoko.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Tomo-chan wa Onnanoko!",
      status: "Finalizado",
      availability: "Disponible 13 capitulos",
    },
    {
      imageSrc: "../img/2023/oniichan-wa-oshimai.jpg",
      dateAdded: "2023",
      dateOfRelease: "Fecha de emisión",
      name: "Oniichan wa Oshimai!",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/kaguya-sama-wa-kokurasetai-first-kiss-wa-owaranai.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Kaguya-sama wa Kokurasetai: First Kiss wa Owaranai",
      status: "Finalizado",
      availability: "Disponible 4 capitulos",
    },
    {
      imageSrc: "../img/2022/tensei-shitara-slime-datta-ken-movie-guren-no-kizuna-hen.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Tensei shitara Slime Datta Ken Movie: Guren no Kizuna-hen",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/tonikaku-kawaii-seifuku.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Tonikaku Kawaii: Seifuku",
      status: "Finalizado",
      availability: "Disponible 1 capitulo",
    },
    {
      imageSrc: "../img/2022/suzume-no-tojimari.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Suzume no Tojimari",
      status: "Finalizado",
      availability: "Disponible 1 capitulo",
    },
    {
      imageSrc: "../img/2022/kancolle-itsuka-ano-umi-de.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "KanColle: Itsuka Ano Umi de",
      status: "Finalizado",
      availability: "Disponible 8 capitulos",
    },
    {
      imageSrc: "../img/2022/sword-art-online-progressive-movie-kuraki-yuuyami-no-scherzo.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Sword Art Online: Progressive Movie - Kuraki Yuuyami no Scherzo",
      status: "Finalizado",
      availability: "Disponible 1 capitulo",
    },
    {
      imageSrc: "../img/2022/bocchi-the-rock.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Bocchi the Rock!",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/boku-ga-aishita-subete-no-kimi-e.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 1 capitulo",
    },
    {
      imageSrc: "../img/2022/kimi-wo-aishita-hitori-no-boku-e.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 1 capitulo",
    },
    {
      imageSrc: "../img/2022/mushikaburi-hime.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/kage-no-jitsuryokusha-ni-naritakute.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/tensei-shitara-ken-deshita.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/spy-x-family-part-2.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/boku-no-hero-academia-6th-season.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/d4dj-double-mix.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/yowai-5000-nen-no-soushoku-dragon-iwarenaki-jaryuu-nintei.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/love-live-superstar-2nd-season.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/hataraku-maou-sama-2.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/dr-stone-ryuusui.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/yofukashi-no-uta.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/mamahaha-no-tsurego-ga-motokano-datta.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/kinsou-no-vermeil-gakeppuchi-majutsushi-wa-saikyou-no-yakusai-to-mahou-sekai-wo-tsukisusumu.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/youkoso-jitsuryoku-shijou-shugi-no-kyoushitsu-e-tv-2nd-season.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/engage-kiss.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/kanojo-okarishimasu-2nd-season.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/lycoris-recoil.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/boku-no-hero-academia-ona.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/dragon-ball-super-super-hero.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/5-toubun-no-hanayome-movie.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/kakkou-no-iinazuke.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/kawaii-dake-ja-nai-shikimori-san.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/spy-x-family.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/komi-san-wa-comyushou-desu-2nd-season.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/date-a-live-iv.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/shijou-saikyou-no-daimaou-murabito-a-ni-tensei-suru.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/tate-no-yuusha-no-nariagari-season-2.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/build-divide-code-white.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/blackrock-shooter-dawn-fall.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/rikei-ga-koi-ni-ochita-no-de-shoumei-shitemita-heart.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/aharen-san-wa-hakarenai.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/love-live-nijigasaki-gakuen-school-idol-doukoukai-2nd-season.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/kaguya-sama-wa-kokurasetai-ultra-romantic.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/strike-the-blood-final.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/arifureta-shokugyou-de-sekai-saikyou-2nd-season-special.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/fruits-basket-prelude.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/kobayashi-san-chi-no-maidragon-s-nippon-no-omotenashi-attend-wa-dragon-desu.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/arifureta-shokugyou-de-sekai-saikyou-2nd-season.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2022/princess-connect-redive-season-2.jpg",
      dateAdded: "2022",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/bang-dream-movie-poppin-dream.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/mahouka-koukou-no-rettousei-tsuioku-hen.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/sword-art-online-progressive-movie-hoshi-naki-yoru-no-aria.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/180-byou-de-kimi-no-mimi-wo-shiawase-ni-dekiru-ka.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/kaginado.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/build-divide-code-black.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/komi-san-wa-comyushou-desu.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/shin-no-nakama-ja-nai-to-yuusha-no-party-wo-oidasareta-node-henkyou-de-slow-life-suru-koto-ni-shimashita.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/takt-op-destiny.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/puraore-pride-of-orange.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/shinka-no-mi-shiranai-uchi-ni-kachigumi-jinsei.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/mieruko-chan.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/selection-project.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/otome-game-no-hametsu-flag-shika-nai-akuyaku-reijou-ni-tensei-shiteshimatta-ova.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/mahoutsukai-no-yome-nishi-no-shounen-to-seiran-no-kishi.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/fatekaleid-liner-prismaillya-movie-licht-namae-no-nai-shoujo.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/bang-dream-film-live-2nd-stage.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/tonikaku-kawaii-sns.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/boku-no-hero-academia-the-movie-3-world-heroes-mission.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/jahy-sama-wa-kujikenai.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/megami-ryou-no-ryoubo-kun.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/love-live-superstar.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    
    {
      imageSrc: "../img/2021/kobayashi-san-chi-no-maid-dragon-s.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/tensei-shitara-slime-datta-ken-2nd-season-part-2.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/tantei-wa-mou-shindeiru.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/otome-game-no-hametsu-flag-shika-nai-akuyaku-reijou-ni-tensei-shiteshimatta-x.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/kanojo-mo-kanojo.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/mahouka-koukou-no-yuutousei.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/nanatsu-no-taizai-movie-2-hikari-ni-norowareshi-mono-tachi.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/wonder-egg-priority-special.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/bang-dream-movie-episode-of-roselia-ii-song-i-am.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/shuumatsu-no-walkre.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/sayonara-watashi-no-cramer-movie-first-touch.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/kaguya-sama-wa-kokurasetai-tensai-tachi-no-renai-zunousen-ova.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/bang-dream-movie-episode-of-roselia-i-yakusoku.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/tokyo-revengers.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/mini-dragon.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/fruits-basket-the-final.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/tensura-nikki-tensei-shitara-slime-datta-ken.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/hige-wo-soru-soshite-joshikousei-wo-hirou.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/edens-zero.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/boku-no-hero-academia-5th-season.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/dr-stone-stone-wars.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/wonder-egg-priority.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/nanatsu-no-taizai-fundo-no-shinpan.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/tensei-shitara-slime-datta-ken-2nd-season.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/azur-lane-bisoku-zenshin.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/wixoss-divaalive.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/ore-dake-haireru-kakushi-dungeon.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/yakusoku-no-neverland-2nd-season.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2021/5-toubun-no-hanayome-2.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/date-a-bullet-nightmare-or-queen.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/toji-no-miko-kizamishi-issen-no-tomoshibi-ova.jpg",
      dateAdded: "2021",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/mahouka-koukou-no-rettousei-raihousha-hen.jpg",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/munou-na-nana.jpg",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/tonikaku-kawaii.jpg",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/rail-romanesque.jpg",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/love-live-nijigasaki-gakuen-school-idol-doukoukai.jpg",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/ochikobore-fruit-tart.jpg",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/violet-evergarden-movie.jpg",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/boku-no-hero-academia-ikinokore-kesshi-no-survival-kunren.jpg",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/date-a-bullet-dead-or-bullet.jpg",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/sword-art-online-alicization-war-of-underworld-2nd-season.jpg",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/kanojo-okarishimasu.jpg",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/yahari-ore-no-seishun-love-comedy-wa-machigatteiru-kan.jpg",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/the-god-of-high-school.jpg",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/lapis-relights.jpg",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/maou-gakuin-no-futekigousha-shijou-saikyou-no-maou-no-shiso-tensei-shite-shison-tachi-no-gakkou-e.jpg",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/kaguya-sama-wa-kokurasetai-tensai-tachi-no-renai-zunousen-2.jpg",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    },
    {
      imageSrc: "../img/2020/",
      dateAdded: "2020",
      dateOfRelease: "Fecha de emisión",
      name: "Nombre del anime",
      status: "Finalizado",
      availability: "Disponible 12 capitulos",
    }
     // Agrega más objetos según sea necesario
];
// Función para agregar una tarjeta al contenedor
// Función para agregar una tarjeta al contenedor
function addCard(cardData, index) {
  const cardsContainer = document.getElementById("cardsContainer");

  // Modifica la condición para incluir las tarjetas deseadas
  const isSpecialCard = [].includes(index);

  const cardHTML = `
    <div class="p-4 sm:w-1/2 lg:w-1/4 ${isSpecialCard ? 'bg-gradient-to-r from-yellow-500 to-red-500 text-white' : 'bg-white text-black'} mx-auto">
      <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
        <img class="lg:h-72 md:h-48 w-full object-cover object-center" src="${cardData.imageSrc}" alt="blog">
        <div class="p-6">
          <h2 class="text-base font-medium text-indigo-300 mb-1">${cardData.dateAdded}</h2>
          <h2 class="text-base font-medium text-indigo-300 mb-1">${cardData.dateOfRelease}</h2>
          <h1 class="text-2xl font-semibold mb-3">${cardData.name}</h1>
          <h3 class="text-black hover:bg-gradient-to-l focus:ring-4 focus:outline-none focus:ring-purple-200 dark:focus:ring-purple-800 font-medium rounded-lg text-sm px-0 py-2.5 ">${cardData.status}</h3>
          <li class="py-3 sm:py-4">
            <div class="flex items-center space-x-3">
              <span class="inline-flex items-center bg-green-100 text-green-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-green-900 dark:text-green-300">
                ${cardData.availability}
              </span>
            </div>
          </li>
          <div class="flex items-center flex-wrap">
            <a href="#" class="${isSpecialCard ? 'text-orange-400' : 'text-blue-600'} inline-flex items-center md:mb-2 lg:mb-0">Read More
              <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path d="M5 12h14"></path>
                <path d="M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
  `;

  cardsContainer.innerHTML += cardHTML;
  }
  
  // Agrega las tarjetas iniciales
  cardsData.forEach(addCard);
  
  // Evento para agregar una nueva tarjeta al hacer clic en el botón
  document.getElementById("addCardBtn").addEventListener("click", () => {
    const newCardData = {
      // Datos para la nueva tarjeta
    };
    addCard(newCardData);
  });
  
  document.addEventListener('DOMContentLoaded', function () {
    const dropdownButton = document.getElementById('dropdownButton');
    const dropdownContent = document.getElementById('dropdownContent');
  
    dropdownButton.addEventListener('click', () => {
      dropdownContent.classList.toggle('hidden');
    });
  
    // Cerrar la lista desplegable si se hace clic fuera de ella
    document.addEventListener('click', (event) => {
      if (!dropdownButton.contains(event.target) && !dropdownContent.contains(event.target)) {
        dropdownContent.classList.add('hidden');
      }
    });
  });